spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kimyo_db
    username: kimyo_user
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /auth-service
  port: 8031

springdoc:
  api-docs.path: /api-docs

